### ISSUE TITLE
active_token not set

### ISSUE THREAD

**Issue by spint** [lancejpollard/authlogic-connect#16]
I'm using the plugin to connect to google Oauth. 
It is working fine, user and token are created but once logged in, the active token is not set: 
'active_token_id' in User and 'active' flag in AccessToken remain 'nil'.

It seems that the method 'complete_oauth_transaction' in authlogic_connect/oauth/user.rb is never called, the one in authlogic_conncet/oauth/session.rb is called fine.

Any idea what is happening ?

**Comment by lancejpollard** [comment]
I'm looking into this.  Thanks!

**Comment by lancejpollard** [comment]
I think I am going to get rid of the `active_token` idea.  This is a very customizable area, if you have any ideas let me know.

Instead of the `active_token`, maybe just finding the token by most current `updated_at`, or by your apps preference (say you prefer having users login through facebook over twitter).  So you can create an `active_token` method that returns what you need.

Hope that helps,
Lance

**Comment by spint** [comment]
It's definitely not critical for me since I'm only using google as oauth provider :-)
Thanks for your reply!
