### ISSUE TITLE
Error installing on Rails 2.3.8

### ISSUE THREAD

**Issue by daft** [lancejpollard/authlogic-connect#40]
When attempting to install via:

sudo gem install authlogic-connect 

on Rails 2.3.8, one is presented with this message:

Building native extensions.  This could take a while...
ERROR:  Error installing authlogic-connect:
    activemodel requires activesupport (= 3.0.0, runtime)

Thoughts?

**Comment by lancejpollard** [comment]
I just installed it on my Rails 2.3.8 gemset and it installed fine.  I think it's probably because you have both rails 2.3.8 and rails 3x installed on your system.  I ran into a similar problem in a different situation before, in which through the dependency loading magic that happens in the background, the most current version of activerecord/activesupport is loaded, instead of the one I wanted.

I suggest using [RVM](http://rvm.beginrescueend.com/) if you're not already, or just uninstall all rails 3 gems from your system, and it'll work fine.

**Comment by daft** [comment]
Hm.  Totally weird.  I only have one version of rails installed (as confirmed by "gems list rails").  Further when I try to add it to my .gems manifest in my heroku app, and heroku attempts to download it, it chokes there as well.  BUT, when check using "rake gems" I see it installed.  Weird stuff indeed.  While looking around I found a similar issue over at the formtastic listing available here: http://github.com/justinfrench/formtastic/issues/closed/#issue/364

Moral of the story?  Use bundler for older rails installations.

**Comment by daft** [comment]
Closing this.

**Comment by hotrannam** [comment]
Hi, 
 I am working on rails version 3.0.0. I got error when installing authlogic-connect, it said that 'activemodel requires activesupport (= 3.0.3, runtime)'.

I checked version of dependencies, it only requires version 2.1.2 of active-support. Thought?

Thanks.
